from michie.mappers.globalmapper import GlobalMapper
from michie.mappers.statemapper import StateMapper
from michie.mappers.distances import DistancesGlobalMapper
from michie.mappers.neighbours import NeighboursStateMapperFactory